### ISSUE TITLE
Value params

### ISSUE THREAD

**Issue by mattapperson** [liftsecurity/sorrow#1]
It would be useful, if not required to be able to pass in things like string min length, max, exact, a regex pattern... but not just a string, any value type... basically let any params be passed in that would pass joi validation. Because if the value does not pass then Joi would reject it thus a none threat.

**Comment by jlamendo** [comment]
Just added with my last commit. 
Currently, it's working for everything with the exception of .any/.object/.array. 
Requires the use of the async api - I'm considering deprecating the sync api entirely though. It was quite useful at the start of the module, but at this point it simply removes access to many useful features, and adds additional work to maintenance. 

In lieu of proper docs because I don't have the time to add them right now, to use the new min/max features:

```
//primitives only - objects are planned for the near future.
sorrow.async.string( seedValue || null, {min:10, max:100}, cb || null  )
```

Leaving open until I can add non-primitives and the remaining Joi functionality.

**Comment by jlamendo** [comment]
Alright, as requested @mattapperson! 
You can now limit min/max lengths for all fuzz types, provide an exact value ( only within non-primitives - if you need to inject an exact string, it doesn't need to be run through the fuzzer, just inject it as is.), etc. 

I'm going to leave regex expansion out for now - that's a project in and of itself. Also, I'm currently working on wrapping the module up into a web service, and that has some negative implications when it comes to performance and introduces the potential for Regular Expression Denial of Service. It should suffice in most cases to throw a string that passes the regex into the mutator.

To use the new non-primitive features, as well as the exact feature:
The property names are particular, and reserved for internal fuzzer use.

```
var sorrow = require('sorrow');
sorrow.async.object({
    "Joi().exact": {
        "_immutable": "static value - will be returned exactly as is, for Joi.exact."
    }, 
    "Per-KV-Min/Max Generators": {
        "_min":10,
        "_max": 1000,
        "_type": "string" // Any valid sorrow type works here
        },
    "Per-KV-Min/Max Mutators": {
        "_min":10,
        "_max": 1000,
        "_type": "string", // Any valid sorrow type works here. 
        "_seed": "Some String to be mutated"
    }, 
      "Simple Nested Generator": "string",
      "Simple Nested Generator Two": "binary",
})

```

Keep in mind, doing things like making a date object with a min of 1 isn't going to validate ever, because 1 character can't be a valid date, but all reasonable use cases should be go. Currently in the process of writing up tests and docs for the new features.

Closing for now.
